INSERT INTO product_inventory VALUES(100, 25, 'Tin', 350, 'Farex', 'Powder', 'Baby Product');
INSERT INTO product_inventory VALUES(101, 155, 'Refill Pack', 202, 'Boost', 'Powder', 'Food');
INSERT INTO product_inventory VALUES(102, 30, 'Bottle', 2570, 'Lacoste', 'Liquid', 'Perfume');
INSERT INTO product_inventory VALUES(103, 155, 'Plastic Container', 175, 'Surf', 'Powder', 'Washing');
INSERT INTO product_inventory VALUES(104, 125, 'Refill Package', 259, 'Ariel', 'Powder', 'Washing');
INSERT INTO product_inventory VALUES(105, 225, 'Wrapper', 32, 'Hamam', 'Solid', 'Bathing');
INSERT INTO product_inventory VALUES(106, 745, 'Plastic Container', 105, 'Head and Shoulders', 'Liquid', 'Bathing');
INSERT INTO product_inventory VALUES(107, 810, 'Refill Pack', 215, 'Horlicks', 'Powder', 'Food');
INSERT INTO product_inventory VALUES(108, 650, 'Tin', 369, 'Lactose', 'Powder', 'Baby Product');
INSERT INTO product_inventory VALUES(109, 358, 'Tin', 165, 'Axe', 'Liquid', 'Perfume');
INSERT INTO product_inventory VALUES(110, 455, 'Plastic Container', 350, 'Bio Washing Liquid', 'Liquid', 'Washing');
INSERT INTO product_inventory VALUES(111, 258, 'Bottle', 222, 'Boost', 'Powder', 'Food');
INSERT INTO product_inventory VALUES(112, 256, 'Bottle', 235, 'Horlicks', 'Powder', 'Food');
INSERT INTO product_inventory VALUES(113, 2850, 'Polycover pack', 32, 'Cumin Seeds', 'Solid', 'Food');
INSERT INTO product_inventory VALUES(114, 2655, 'Polycover pack', 14, 'Mustard Seeds', 'Solid', 'Food');
INSERT INTO product_inventory VALUES(115, 2755, 'Polycover pack', 15, 'Fenugreek Seeds', 'Solid', 'Food');
COMMIT;
